### ISSUE TITLE
Monitoring support for external resources

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-provbz#19]
Currently Google Analitycs is used to check the access to the Ckan pages and internal resources.
External resources cannot be monitored with GA like the following:

http://dati.retecivica.bz.it/it/dataset/farmacie-di-turno-dell-alto-adige1/resource/21dfaa80-a267-4f2b-8cdc-97a576e777be

We need to provide a new Ckan API to retrieve the list (in human readable format like JSON) of the URL of external resources to be monitored by external tools.

The same feature should be implemented also for the other customer [datitrentinoit](https://github.com/geosolutions-it/ckanext-datitrentinoit/tree/dcatapit), so probably the best way to proceed will be to create a new ckan extension with a plugin that provides this functionality (this to avoid code replication between two Ckan's extenstion: provbz and datitrentinoit)

**Comment by cezio** [comment]
Implemented in https://github.com/geosolutions-it/ckanext-extras/ as `external_resource_list` action. It's available in API: http://localhost:5000/api/action/external_resource_list

Optional params with defaults: `limit=50`, `offset=0`

Returned data is a list of dictionaries:

```
{"help": "http://localhost:5000/api/3/action/help_show?name=external_resource_list", 
  "success": true,
   "result": [
        {"url": "http://dati.cittametropolitana.fi.it/dataset/38166a85-619a-4510-9bf7-2aa4d606a629/resource/1455c184-c9e4-4012-ac3a-10003f37901b/download/dataset2012.xml",
        "dataset_url": "http://dati.cittametropolitama.fi.it/dataset/pubblicazione-ai-sensi-della-legge-anticorruzione", 
         "name": "2012 - Pubblicazione ai sensi della \"Legge anticorruzione\"",
         "dataset": "Pubblicazione ai sensi dell'art. 1, co. 32 della L. 190/2012 (\"Legge anticorruzione\") - Citt\u00e0 Metropolitana di Firenze"}, ...]}
```

Tests are not yet completed.

**Comment by cezio** [comment]
Simple test case added, also added travis configuration.

**Comment by tdipisa** [comment]
@cezio, thank you I will check asap

**Comment by tdipisa** [comment]
@cezio, there is something wrong I think.

Please, see the output at the URL below:
http://opendata-trento.geo-solutions.it/api/action/external_resource_list?limit=10&offset=2

For example the following resource:

{
     "url": "bibliotechetrentinocbtschema.zip",
     "dataset_url": "http://www.cbt.biblioteche.provincia.tn.it/oseegenius/download-orari-biblioteche.vm",
      "name": "Biblioteche del Trentino SCHEMA",
      "dataset": "Biblioteche del Trentino"
}

**url **: must be the [complete URL](
http://opendata-trento.geo-solutions.it/dataset/60783e19-7e06-4c80-9c5f-3a04bbc35981/resource/7ccdedbd-a5b5-4e07-a9b3-e74dec6c9dfe/download/bibliotechetrentinocbtschema.zip) of the resource reachable from external monitoring systems

**dataset_url**:  what is this URL? This property should point to the [URL of the dataset](http://opendata-trento.geo-solutions.it/dataset/anagrafica-biblioteche) .

**name**: OK

**dataset**: unneeded since we have the URL

**Can we include also the total resource count in the output?**

**Comment by cezio** [comment]
> **url **: must be the complete URL of the resource reachable from external monitoring systems

This is a value stored in resource. I didn't modify it in any way. But that shouldn't be a problem, I'll add site's base url if it's missing.

> dataset_url: what is this URL? This property should point to the URL of the dataset .

This is dataset's url property. Again, not modified in any way. If you'll visit this specific url, it looks like a dataset description (although it's not served from CKAN instance).

**Comment by tdipisa** [comment]
@cezio, I don't think so. That's the URL returning the JSON output of this resource using the Ckan's API:

**Comment by cezio** [comment]
> @cezio, I don't think so. That's the URL returning the JSON output of this resource using the Ckan's API:

That's because I don't use `resource_show` api internally. I'll check it's implementation and correct links though.

**Comment by cezio** [comment]
@tdipisa related PR: https://github.com/geosolutions-it/ckanext-extras/pull/1

**Comment by tdipisa** [comment]
Hello @cezio, 

here:
http://188.165.62.180/api/action/external_resource_list?limit=50&offset=2

we have some resources collected in the output with an URL like the following:

http://dati.retecivica.bz.it/services/kksSearch/collect/select?q=*:*&fl=*&rows=100&wt=json

in that case the domain is the same but I know that the resource is external.
As far as I can see [you are checking the site_url in config](https://github.com/geosolutions-it/ckanext-extras/blob/master/ckanext/extras/helpers.py#L36), but since in PROD configuration
we have:

site_url = http://dati.retecivica.bz.it/

the type of resource I mentioned is not collected in the output. Can we introduce maybe in the .ini a specific config to be able to specify some custom regex that can be used by the ckanext-extras for the URL check?

**Comment by cezio** [comment]
Sure. I was using site_url comparison, because it's basically the way ckan recognizes local/remote urls (https://github.com/ckan/ckan/blob/ckan-2.5.7/ckan/lib/helpers.py#L333-L342). 

I'll add `ckanext.extras.local_sites` setting which will be a list of strings or regexes.

**Comment by cezio** [comment]
> I'll add ckanext.extras.local_sites setting which will be a list of strings or regexes.

Actually, using regexp here would be a bit problematic, because this list will be feed db query to exclude local resources.

I've added handling of `ckanext.extras.local_sites` config var. It can be a list of strings for now.

**Comment by tdipisa** [comment]
@cezio, where I can find your updates? there's not a PR

**Comment by cezio** [comment]
https://github.com/geosolutions-it/ckanext-extras/pull/2

**Comment by tdipisa** [comment]
@cezio, this solution sounds good, please can you also add to the PR a commits with some updates to the README containing a description/explanation of the available settings in .ini file ?

**Comment by cezio** [comment]
@cezio, this solution sounds good, please can you also add to the PR a commits with some updates to the README containing a description/explanation of the available settings in .ini file ?

Added in https://github.com/geosolutions-it/ckanext-extras/pull/2/commits/317aaf05d9bdfde268b188c571288acba0b5165d

**Comment by cezio** [comment]
local/external link detection improvements added. please review.

**Comment by tdipisa** [comment]
@cezio, the latest update generate the error below.

The request URL is the following:
http://188.165.62.180/api/action/external_resource_list?limit=50&offset=2

Error - <class 'sqlalchemy.exc.ProgrammingError'>: (ProgrammingError) syntax error at or near "ORDER"
LINE 4: ...R (resource.url LIKE 'https://' || '%')) AND NOT  ORDER BY r...
                                                             ^
 "SELECT count(*) AS count_1 \nFROM (SELECT resource.id AS resource_id, resource.package_id AS resource_package_id, resource.url AS resource_url, resource.format AS resource_format, resource.description AS resource_description, resource.hash AS resource_hash, resource.position AS resource_position, resource.name AS resource_name, resource.resource_type AS resource_resource_type, resource.mimetype AS resource_mimetype, resource.mimetype_inner AS resource_mimetype_inner, resource.size AS resource_size, resource.created AS resource_created, resource.last_modified AS resource_last_modified, resource.cache_url AS resource_cache_url, resource.cache_last_updated AS resource_cache_last_updated, resource.webstore_url AS resource_webstore_url, resource.webstore_last_updated AS resource_webstore_last_updated, resource.url_type AS resource_url_type, resource.extras AS resource_extras, resource.state AS resource_state, resource.revision_id AS resource_revision_id, package.id AS package_id, package.name AS package_name, package.title AS package_title, package.version AS package_version, package.url AS package_url, package.author AS package_author, package.author_email AS package_author_email, package.maintainer AS package_maintainer, package.maintainer_email AS package_maintainer_email, package.notes AS package_notes, package.license_id AS package_license_id, package.type AS package_type, package.owner_org AS package_owner_org, package.creator_user_id AS package_creator_user_id, package.metadata_modified AS package_metadata_modified, package.private AS package_private, package.state AS package_state, package.revision_id AS package_revision_id \nFROM resource JOIN package ON package.id = resource.package_id \nWHERE package.state = %(state_1)s AND package.private IS false AND resource.state = %(state_2)s AND ((resource.url LIKE %(url_1)s || '%%') OR (resource.url LIKE %(url_2)s || '%%')) AND NOT  ORDER BY resource.url) AS anon_1" {'state_1': 'active', 'state_2': 'active', 'url_2': 'https://', 'url_1': 'http://'}
URL: http://localhost:5000/api/action/external_resource_list?limit=50&offset=2
File '/usr/lib/ckan/default/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py', line 389 in inner
  result = application(environ, start_response)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/api.py', line 70 in __call__
  return base.BaseController.__call__(self, environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 338 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/api.py', line 197 in action
  result = function(context, request_data)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 431 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 547 in wrapper
  return action(context, data_dict)
File '/usr/lib/ckan/default/src/ckanext-extras/ckanext/extras/actions.py', line 43 in external_resource_list
  count = q.count()
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2594 in count
  return self.from_self(col).scalar()
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2393 in scalar
  ret = self.one()
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2362 in one
  ret = list(self)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2405 in __iter__
  return self._execute_and_instances(context)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2420 in _execute_and_instances
  result = conn.execute(querycontext.statement, self._params)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 727 in execute
  return meth(self, multiparams, params)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/sql/elements.py', line 322 in _execute_on_connection
  return connection._execute_clauseelement(self, multiparams, params)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 824 in _execute_clauseelement
  compiled_sql, distilled_params
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 954 in _execute_context
  context)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 1116 in _handle_dbapi_exception
  exc_info
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/util/compat.py', line 189 in raise_from_cause
  reraise(type(exception), exception, tb=exc_tb)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 947 in _execute_context
  context)
File '/usr/lib/ckan/default/lib/python2.7/site-packages/sqlalchemy/engine/default.py', line 435 in do_execute
  cursor.execute(statement, parameters)
ProgrammingError: (ProgrammingError) syntax error at or near "ORDER"
LINE 4: ...R (resource.url LIKE 'https://' || '%')) AND NOT  ORDER BY r...
                                                             ^
 "SELECT count(*) AS count_1 \nFROM (SELECT resource.id AS resource_id, resource.package_id AS resource_package_id, resource.url AS resource_url, resource.format AS resource_format, resource.description AS resource_description, resource.hash AS resource_hash, resource.position AS resource_position, resource.name AS resource_name, resource.resource_type AS resource_resource_type, resource.mimetype AS resource_mimetype, resource.mimetype_inner AS resource_mimetype_inner, resource.size AS resource_size, resource.created AS resource_created, resource.last_modified AS resource_last_modified, resource.cache_url AS resource_cache_url, resource.cache_last_updated AS resource_cache_last_updated, resource.webstore_url AS resource_webstore_url, resource.webstore_last_updated AS resource_webstore_last_updated, resource.url_type AS resource_url_type, resource.extras AS resource_extras, resource.state AS resource_state, resource.revision_id AS resource_revision_id, package.id AS package_id, package.name AS package_name, package.title AS package_title, package.version AS package_version, package.url AS package_url, package.author AS package_author, package.author_email AS package_author_email, package.maintainer AS package_maintainer, package.maintainer_email AS package_maintainer_email, package.notes AS package_notes, package.license_id AS package_license_id, package.type AS package_type, package.owner_org AS package_owner_org, package.creator_user_id AS package_creator_user_id, package.metadata_modified AS package_metadata_modified, package.private AS package_private, package.state AS package_state, package.revision_id AS package_revision_id \nFROM resource JOIN package ON package.id = resource.package_id \nWHERE package.state = %(state_1)s AND package.private IS false AND resource.state = %(state_2)s AND ((resource.url LIKE %(url_1)s || '%%') OR (resource.url LIKE %(url_2)s || '%%')) AND NOT  ORDER BY resource.url) AS anon_1" {'state_1': 'active', 'state_2': 'active', 'url_2': 'https://', 'url_1': 'http://'}


CGI Variables
-------------
  AUTH_TYPE: 'cookie'
  CKAN_CURRENT_URL: '/api/action/external_resource_list?limit%3D50%26offset%3D2'
  CKAN_LANG: 'it'
  CKAN_LANG_IS_DEFAULT: True
  CONTENT_LENGTH: '0'
  CONTENT_TYPE: '; charset=utf-8'
  HTTP_ACCEPT: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8'
  HTTP_ACCEPT_ENCODING: 'gzip, deflate'
  HTTP_ACCEPT_LANGUAGE: 'it,en-US;q=0.9,en;q=0.8'
  HTTP_CACHE_CONTROL: 'max-age=0'
  HTTP_CONNECTION: 'Keep-Alive'
  HTTP_COOKIE: '_ga=GA1.1.184663191.1516981107; displayCookieConsent=y; auth_tkt="792187f6595b76636b8ed1b291895cad5a818430admin!userid_type:unicode"'
  HTTP_HOST: 'localhost:5000'
  HTTP_UPGRADE_INSECURE_REQUESTS: '1'
  HTTP_USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'
  HTTP_X_FORWARDED_FOR: '79.135.50.112'
  HTTP_X_FORWARDED_HOST: '188.165.62.180'
  HTTP_X_FORWARDED_SERVER: '127.0.0.1'
  PATH_INFO: '/api/action/external_resource_list'
  QUERY_STRING: 'limit=50&offset=2'
  REMOTE_ADDR: '127.0.0.1'
  REMOTE_USER: u'admin'
  REMOTE_USER_DATA: 'userid_type:unicode'
  REMOTE_USER_TOKENS: ['']
  REQUEST_METHOD: 'GET'
  SERVER_NAME: '0.0.0.0'
  SERVER_PORT: '5000'
  SERVER_PROTOCOL: 'HTTP/1.1'


WSGI Variables
--------------
  application: <fanstatic.publisher.Delegator object at 0x5fcc690>
  beaker.cache: <beaker.cache.CacheManager object at 0x5fcc2d0>
  beaker.get_session: <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x5fcf310>>
  beaker.session: {'_accessed_time': 1518786026.556276, '_creation_time': 1518786026.556276}
  fanstatic.needed: <fanstatic.core.NeededResources object at 0x7f24d85ac490>
  paste.cookies: (<SimpleCookie: _ga='GA1.1.184663191.1516981107' auth_tkt='792187f6595b76636b8ed1b291895cad5a818430admin!userid_type:unicode' displayCookieConsent='y'>, '_ga=GA1.1.184663191.1516981107; displayCookieConsent=y; auth_tkt="792187f6595b76636b8ed1b291895cad5a818430admin!userid_type:unicode"')
  paste.httpserver.thread_pool: <paste.httpserver.ThreadPool object at 0x2307910>
  paste.parsed_dict_querystring: (MultiDict([('limit', '50'), ('offset', '2')]), 'limit=50&offset=2')
  paste.parsed_querystring: ([('limit', '50'), ('offset', '2')], 'limit=50&offset=2')
  paste.registry: <paste.registry.Registry object at 0x7f24d8455590>
  paste.throw_errors: True
  pylons.action_method: <bound method ApiController.action of <ckan.controllers.api.ApiController object at 0x7f24d85ac7d0>>
  pylons.controller: <ckan.controllers.api.ApiController object at 0x7f24d85ac7d0>
  pylons.environ_config: {'session': 'beaker.session', 'cache': 'beaker.cache'}
  pylons.pylons: <pylons.util.PylonsContext object at 0x7f24d85ac710>
  pylons.routes_dict: {'action': u'action', 'controller': u'api', 'ver': 3, 'logic_function': u'external_resource_list'}
  pylons.status_code_redirect: True
  repoze.who.api: <repoze.who.api.API object at 0x7f24d8455550>
  repoze.who.identity: <repoze.who identity (hidden, dict-like) at 139795951017888>
  repoze.who.logger: <logging.Logger object at 0x5fd3110>
  repoze.who.plugins: {'ckan.lib.authenticator:UsernamePasswordAuthenticator': <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x5fcc310>, 'friendlyform': <FriendlyFormPlugin 101802768>, 'auth_tkt': <CkanAuthTktCookiePlugin 101802704>}
  routes.route: <routes.route.Route object at 0x5d4fdd0>
  routes.url: <routes.util.URLGenerator object at 0x7f24d844cc90>
  webob._parsed_query_vars: (GET([('limit', '50'), ('offset', '2')]), 'limit=50&offset=2')
  webob.adhoc_attrs: {'response': <Response at 0x7f24d85ac590 200 OK>, 'language': 'en-us'}
  wsgi process: 'Multithreaded'
  wsgiorg.routing_args: (<routes.util.URLGenerator object at 0x7f24d844cc90>, {'action': u'action', 'controller': u'api', 'ver': 3, 'logic_function': u'external_resource_list'})
------------------------------------------------------------
2018-02-16 14:00:26,557 INFO  [repoze.who] no challenge required
2018-02-16 14:00:26,557 INFO  [repoze.who] -- repoze.who request ended (/api/action/external_resource_list) --
2018-02-16 14:00:26,693 INFO  [repoze.who] request classification: browser
2018-02-16 14:00:26,693 INFO  [repoze.who] -- repoze.who request started (/favicon.ico) --
2018-02-16 14:00:26,694 INFO  [repoze.who] no challenge required
2018-02-16 14:00:26,694 INFO  [repoze.who] -- repoze.who request ended (/favicon.ico) -

**Comment by cezio** [comment]
1. https://github.com/geosolutions-it/ckanext-extras/pull/3
2. there was a misconfiguration on the host, you had `ckanext.extras.*` twice in configuration file. I've commented first entry, and reformatted the other. Additionally, i've added one exclusion from the list, resources that have url value starting with `/` (included in PR).
