### ISSUE TITLE
Resource download

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-provbz#23]
If the resource preview is missing for some reason a download button appears  in the preview panel. Below the URL of a dataset to use as reference:

http://dati.retecivica.bz.it/it/dataset/italian-pollnet-webservices/resource/1db34ff4-c3df-4d04-a6ec-570b4a89772d

In this case the button '**Scarica la risorsa**' does not produce the download of the resource but simply refresh the page. This button must download the resource.

![clipboard01](https://user-images.githubusercontent.com/1280027/35380569-f369b930-01b9-11e8-9a99-654ffef39cc7.png)

This work should be fixed in the client's extension, that uses an old ckan version (2.4)

**Comment by cezio** [comment]
is this only for ckanext-provbz ?

**Comment by tdipisa** [comment]
@cezio yes, as you can see we have only the label C029

**Comment by tdipisa** [comment]
We can use the following dataset for testing:

http://188.165.62.180/dataset/italian-pollnet-webservices/resource/1db34ff4-c3df-4d04-a6ec-570b4a89772d
