### ISSUE TITLE
Improve the CSV preview

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-provbz#24]
There are some limitations in previewing CSV resources with comma different separator. This problem should be fixed using the datapusher extension.
 
Try previewing this resource:

https://www.europeandataportal.eu/data/dataset/dati-occupazionali-progettone-2012/resource/fb159522-c2c3-4514-a47b-b4f24fb4a384

and this resource in the C029 catalog:
http://dati.retecivica.bz.it/it/dataset/catalogo-beni-culturali/resource/eda81921-060f-4436-bc43-4cfe57e52a17

The customer has no datapusher installed

**Comment by cezio** [comment]
I've tested resource locally with datapusher enabled. It works fine with that extension enabled:

![image](https://user-images.githubusercontent.com/116021/35330120-9c839008-0102-11e8-83d8-21a18fcf162d.png)

I noticed that Format in resource is set to 'csv-semicolon delimited', and there's no Distribution format set. Sibling resource has both fields set to CSV, and working visualization.

**Comment by tdipisa** [comment]
@cezio please can you do a quick check to know if datapusher can be installed within ckan 2.5.2 and ckan 2.4.0? Next step will be planning the installation of this extension in the customer's test environment

**Comment by cezio** [comment]
i've installed datapusher with ckan 2.5.7 (and master branch for datapusher). Checking if this works with ckan 2.4

**Comment by tdipisa** [comment]
@cezio ok thank you, I think we should prepare just a **quick** doc for this, containing the steps to follow during the deploy in the customer environment, or maybe the @etj documentation I shared with you it's enough for this?

**Comment by cezio** [comment]
docs from @etj is sufficient imho, unless it's deployed with other stack than apache+mod_wsgi

**Comment by tdipisa** [comment]
@cezio ok sounds good.

**Comment by tdipisa** [comment]
@Cezio it seems that there are problems with datapusher now. Please can you check on test server? 

resource link below:

http://188.165.62.180/dataset/servizi-web-del-catalogo-dei-beni-culturali-in-alto-adige/resource/fe91898e-47a3-48c2-a578-2ff05654a0d1

**Comment by cezio** [comment]
Should work now

**Comment by cezio** [comment]
should work now

**Comment by cezio** [comment]
For the record, do update existing resources:

```
$ paster datapusher -h
Usage: paster datapusher [options] Perform commands in the datapusher

    Usage:

        resubmit  - Resubmit all datastore resources to the datapusher,
                    ignoring if their files haven't changed.
        submit <pkgname> - Submits all resources from the package
                         identified by pkgname (either the short name or ID)
   
Perform commands in the datapusher

Options:
  -h, --help            show this help message and exit
  -v, --verbose         
  -c CONFIG, --config=CONFIG
                        Config file to use.
  -f FILE_PATH, --file=FILE_PATH
                        File to dump results to (if needed)
```
