### ISSUE TITLE
Broken link in Home page

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-provbz#25]
Fix the broken URL in [Ckan's Home page](http://dati.retecivica.bz.it/it/) (see the footer)

Link text: "CKAN API"
Current URL to fix: http://docs.ckan.org/en/ckan-2.4.0/api.html

**Comment by cezio** [comment]
What should be correct one?

**Comment by tdipisa** [comment]
Use the following URL for C029:

**Comment by cezio** [comment]
PRs:
https://github.com/geosolutions-it/ckanext-datitrentinoit/pull/19
https://github.com/geosolutions-it/ckanext-provbz/pull/27

**Comment by tdipisa** [comment]
@cezio, this seems not fixed yet, look [here](http://188.165.62.180/)
Clicking on the 'CKAN API' link I'm redirected to:

http://docs.ckan.org/en/ckan-2.4.0/api/index.html

**Comment by cezio** [comment]
This url is generated based on ckan version installed.
