### ISSUE TITLE
Private dataset not in search list

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-provbz#53]
Please investigate why private dataset are not visible in dataset search list even if the user is logged as admin.
We have the same issue in the client's instance (ckan 2.4.3), is that a feature of the ckan 2.4.x versions?

**Comment by cezio** [comment]
It seems it's a feature. private datasets are searchable within organization list: https://github.com/ckan/ckan/issues/1239

**Comment by torfsen** [comment]
Note that you can opt-in to showing users their private datasets as of CKAN 2.6, see [this issue](https://github.com/ckan/ckan/issues/2768).
