### ISSUE TITLE
dct:rightsHolder issue between dataset.rdf and catalog.rdf

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/ckanext-provbz#56]
We have differences on **dct:rightsHolder**  between the dataset specific RDF output and the dataset RDF output in catalog.rdf

A sample dataset in client instance [here](http://test-dati.retecivica.bz.it/dataset/servizi-webservice-sasa)

The output of 

http://test-dati.retecivica.bz.it/dataset/servizi-webservice-sasa.rdf  (**the correct one**)

is the following:

    <dct:rightsHolder>
      <foaf:Agent rdf:nodeID="Na91865bc14c94c2b80ed890ccfed8cec">
        <foaf:name xml:lang="de">SASA Bus</foaf:name>
        <foaf:name xml:lang="it">SASA Bus</foaf:name>
        <rdf:type rdf:resource="http://dati.gov.it/onto/dcatapit#Agent"/>
        <foaf:name xml:lang="en">SASA Bus</foaf:name>
        <dct:identifier>00359210218</dct:identifier>
      </foaf:Agent>
    </dct:rightsHolder>

The output in catalog.rdf is the following:

        <dct:rightsHolder>
          <foaf:Agent rdf:nodeID="Ne8276a2d39fe43dd993e46a33fb2b11f">
            <foaf:name xml:lang="it">SASA SpA</foaf:name>
            <foaf:name xml:lang="en">SASA Bus</foaf:name>
            <dct:identifier>tmp_ipa_code_26</dct:identifier>
            <foaf:name xml:lang="de">SASA SpA</foaf:name>
            <foaf:name>SASA Bus</foaf:name>
            <rdf:type rdf:resource="http://dati.gov.it/onto/dcatapit#Agent"/>
          </foaf:Agent>
        </dct:rightsHolder>

**Comment by cezio** [comment]
This was probably because catalog.rdf uses a bit different code path (involing `package_search` instead of `package_show`) to get list of datasets. This was passing dataset locality check, and generating wrong results in the end.
